// Auto-generated by scripts/generate-lab-previews.mjs — do not edit manually.

export const GENERATED_LAB_PREVIEWS: Record<string, string> = {
  "mental-math-practice-module": "/previews/mental-math-practice-module.webm",
  "number-line-integers": "/previews/number-line-integers.webm",
  "vector-addition": "/previews/vector-addition.webm",
};
